---
title: "Validation of Multiple Imputation in SPHC-B 2014"
author: Willi Zhang (willi.zhang@ki.se), Matteo Quartagno
output: html_notebook
editor_options:
  chunk_output_type: inline
---

<br>

##### *Notes:* This document summarizes only the key outputs of the final multiple imputation process for SPHC-B 2014. More detailed R scripts are available in the R Notebook ["SPHC-B-2014.Rmd"](https://github.com/willizhang/Temporal-Trends-in-Sexual-Identity-and-Sociodemographic-Disparities-in-Stockholm-County-2010-to-2021/blob/main/SPHC-B-2014.Rmd).

<br>

### 1. Load Packages
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(naniar)
library(dplyr)
library(jomo)
library(mitml)
library(ggplot2)
```

### 2. SPHC-B 2014
#### 2.1. Incomplete dataset
```{r}
load("/Volumes/LGBT Project data/Multiple Imputation/d_2014_incomplete.RData")
summary( d_2014_incomplete )
sapply( d_2014_incomplete, class ) # all continuous variables are numeric, and all categorical variables are factor
miss_var_summary( d_2014_incomplete ) # 41.2% missing in sexual_identity_fluidity, 9.0% in sexual_identity_2014, 8.2% in personal_support, 7.5% in living_alone, 0.7% in education, and 0.2% in income
```

#### 2.2. Two-level multivariate normal imputation
```{r}
# specify imputation model
# fml_imp_2014 <- sexual_identity_fluidity + sexual_identity_2014 + personal_support + living_alone + education + income ~ 1 + age*sex + country_of_birth + marital_status + ( 1 | weight_strata )

# final imputation with the chosen number of iterations
# imp_final_2014 <- jomoImpute( data = d_2014_incomplete,
#                               formula = fml_imp_2014,
#                               random.L1 = "full",
#                               n.burn = 5000,
#                               n.iter = 2000,
#                               m = 60,
#                               seed = 12345
#                               ) # took around 23 hours

load("/Volumes/LGBT Project data/Multiple Imputation/imp_final_2014.RData")
summary( imp_final_2014 )
plot( imp_final_2014, trace = "all", print = "beta" )
```

#### 2.3. Validate imputed data
```{r}
# extract imputed datasets
original_data_2014 <- mitmlComplete( imp_final_2014, print = 0 ) # extract original incomplete dataset
implist_2014 <- mitmlComplete( imp_final_2014, print = "all" ) # extract all imputed datasets

original_data_2014$imputation <- "0"
all_data_2014 <- bind_rows( original_data_2014, 
                            bind_rows( implist_2014, .id = "imputation" ) ) # merge datasets
all_data_2014$imputation <- as.numeric( all_data_2014$imputation )
summary( all_data_2014 )

# sexual identity in 2014
ggplot( all_data_2014[ !is.na( all_data_2014$sexual_identity_2014 ), ],
        aes( fill = sexual_identity_2014, x = imputation ) ) + 
  geom_bar( position = "fill" ) + 
  scale_y_continuous( labels = scales::percent ) + 
  scale_fill_discrete( name = "Sexual identity in 2014" ) +
  labs(
    x = "Imputation number",
    y = "Proportion",
    caption = "Notes: Imputation number 0 represents the original incomplete dataset." ) +
  theme_classic() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_text( family = "Arial", size = 10 ),
         legend.position = "bottom",
         plot.caption = element_text( family = "Arial", size = 10, hjust = 0 ) 
  )

# change in sexual identity during 2014-2021
ggplot( all_data_2014[ !is.na( all_data_2014$sexual_identity_fluidity ), ],
        aes( fill = sexual_identity_fluidity, x = imputation ) ) + 
  geom_bar( position = "fill" ) + 
  scale_y_continuous( labels = scales::percent ) + 
  scale_fill_discrete( name = "Change in sexual identity during 2014-2021", labels = c( "No", "Yes" ) ) +
  labs(
    x = "Imputation number",
    y = "Proportion",
    caption = "Notes: Imputation number 0 represents the original incomplete dataset." ) +
  theme_classic() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_text( family = "Arial", size = 10 ),
         legend.position = "bottom",
         plot.caption = element_text( family = "Arial", size = 10, hjust = 0 ) 
  )

# education
ggplot( all_data_2014[ !is.na( all_data_2014$education ), ],
        aes( fill = education, x = imputation ) ) + 
  geom_bar( position = "fill" ) + 
  scale_y_continuous( labels = scales::percent ) + 
  scale_fill_discrete( name = "Level of education" ) +
  labs(
    x = "Imputation number",
    y = "Proportion",
    caption = "Notes: Imputation number 0 represents the original incomplete dataset." ) +
  theme_classic() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_text( family = "Arial", size = 10 ),
         legend.position = "bottom",
         plot.caption = element_text( family = "Arial", size = 10, hjust = 0 ) 
  )

# income
summary( all_data_2014$income )
nrow( all_data_2014[ all_data_2014$income < 0 & !is.na( all_data_2014$income ), ] ) #  564 imputed values are negative

# living status
ggplot( all_data_2014[ !is.na( all_data_2014$living_alone ), ],
        aes( fill = living_alone, x = imputation ) ) + 
  geom_bar( position = "fill" ) + 
  scale_y_continuous( labels = scales::percent ) + 
  scale_fill_discrete( name = "Living alone", labels = c( "Yes", "No" ) ) +
  labs(
    x = "Imputation number",
    y = "Proportion",
    caption = "Notes: Imputation number 0 represents the original incomplete dataset." ) +
  theme_classic() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_text( family = "Arial", size = 10 ),
         legend.position = "bottom",
         plot.caption = element_text( family = "Arial", size = 10, hjust = 0 ) 
  )

# personal support
ggplot( all_data_2014[ !is.na( all_data_2014$personal_support ), ],
        aes( fill = personal_support, x = imputation ) ) + 
  geom_bar( position = "fill" ) + 
  scale_y_continuous( labels = scales::percent ) + 
  scale_fill_discrete( name = "Personal support", labels = c( "Yes", "No" ) ) +
  labs(
    x = "Imputation number",
    y = "Proportion",
    caption = "Notes: Imputation number 0 represents the original incomplete dataset." ) +
  theme_classic() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_text( family = "Arial", size = 10 ),
         legend.position = "bottom",
         plot.caption = element_text( family = "Arial", size = 10, hjust = 0 ) 
  )
```